// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// There are two sets of options:
///   - [DevFirebaseOptions] → points at the **alray-dev** Firebase project.
///   - [ProdFirebaseOptions] → points at the **alray-2016** Firebase project.
///
/// Use [getOptionsForFlavor] in each entry-point to pick the correct set.
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DevFirebaseOptions are not configured for web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DevFirebaseOptions are not configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DevFirebaseOptions are not configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DevFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // alray-dev project — matches android/app/src/dev/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvcRUk4ydBu1yiWguZybfeMeH5YTfDR4s',
    appId: '1:319095436768:android:d400838878b845566d6785',
    messagingSenderId: '319095436768',
    projectId: 'alray-dev',
    storageBucket: 'alray-dev.firebasestorage.app',
  );

  // TODO: Add iOS / macOS dev options if you have an iOS dev app in alray-dev.
  // For now, fall back to prod to avoid a crash on those platforms.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADMW8L3CZSOLPEs04kSfanUUEjETErdEw',
    appId: '1:544963390238:ios:f6321dfa6a9465f3ba370f',
    messagingSenderId: '544963390238',
    projectId: 'alray-2016',
    storageBucket: 'alray-2016.firebasestorage.app',
    iosBundleId: 'com.example.alrayApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADMW8L3CZSOLPEs04kSfanUUEjETErdEw',
    appId: '1:544963390238:ios:f6321dfa6a9465f3ba370f',
    messagingSenderId: '544963390238',
    projectId: 'alray-2016',
    storageBucket: 'alray-2016.firebasestorage.app',
    iosBundleId: 'com.example.alrayApp',
  );
}

class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'ProdFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // alray-prod project — matches android/app/src/prod/google-services.json
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvBdKQdbAucMcJBRzOwHzQYt_DzwHUaxI',
    appId: '1:775183573814:android:7cf579945f64a578a2c997',
    messagingSenderId: '775183573814',
    projectId: 'alray-prod',
    storageBucket: 'alray-prod.firebasestorage.app',
  );

  // TODO: Add iOS / macOS prod options once you register an iOS app
  // in the alray-prod Firebase project.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvBdKQdbAucMcJBRzOwHzQYt_DzwHUaxI',
    appId: '1:775183573814:ios:7cf579945f64a578a2c997',
    messagingSenderId: '775183573814',
    projectId: 'alray-prod',
    storageBucket: 'alray-prod.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvBdKQdbAucMcJBRzOwHzQYt_DzwHUaxI',
    appId: '1:775183573814:ios:7cf579945f64a578a2c997',
    messagingSenderId: '775183573814',
    projectId: 'alray-prod',
    storageBucket: 'alray-prod.firebasestorage.app',
  );

  // Web / Windows not yet registered — add these if you need web support
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvBdKQdbAucMcJBRzOwHzQYt_DzwHUaxI',
    appId: '1:775183573814:web:7cf579945f64a578a2c997',
    messagingSenderId: '775183573814',
    projectId: 'alray-prod',
    storageBucket: 'alray-prod.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvBdKQdbAucMcJBRzOwHzQYt_DzwHUaxI',
    appId: '1:775183573814:web:7cf579945f64a578a2c997',
    messagingSenderId: '775183573814',
    projectId: 'alray-prod',
    storageBucket: 'alray-prod.firebasestorage.app',
  );
}

// Keep this alias so any existing imports of DefaultFirebaseOptions still work.
// It resolves to the prod options (the old default).
typedef DefaultFirebaseOptions = ProdFirebaseOptions;
